name: Run checks
on:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: docker compose -f docker/docker-compose.yaml up --detach
      - name: Check formatting
        run: docker exec firebase-admin-sdk cargo fmt --all --check
      - name: Run linter
        run: docker exec firebase-admin-sdk cargo clippy
      - name: Run tests
        run: docker exec firebase-admin-sdk cargo test --lib
      - name: Try building everything
        run: docker exec firebase-admin-sdk cargo build